### ISSUE TITLE
Share Component | Create a 'share' component

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#116]
Once we have functionality up and priority for additional 'nice-to-haves' are higher; let's add global 'url parameter' detection to the views that handle asset selection so that someone can create a 'share' link with for instance 2 assets preselected in 'swap'

Have a think about ways to do it but my off the cuff suggestion is:
- useparams? https://reactrouter.com/web/api/Hooks/useparams
- Use this format: `assets=assetAddress:assetAddress:assetAddress` (chain as many as you want)
- 1st one in the chain will be added to localStorage as 'assetSelected1'
- 2nd one will be added to localStorage as 'assetSelected2'
- And so on (the localStorage variables will be used in the swap/liq management screens)

Then go on to create a way for users to generate a share link easily (as they won't show up in the URL by default; too messy)
- Create 'share' component that adds the param/s to the usual URL based on the assets selected
- User can click the share button and have a dropdown with a link they can click to manually copy/paste or have added to clipboard
- In the dropdown maybe add twitter/socials share link?

### initial planned steps?
- [x] Create 'share' component
- [x] Include a button with 'share' style icon
- [x] Dropdown to include URL and a quick-copy button (or clicking link adds to clipboard?)
- [x] Include social icons to share easily to socials (Twitter etc)

- [x] Create a 'urlParse' component that we will use to parse URL params
- [x] Create an action inside that detects the param format used above and adds the assetAddresses to localStorage in the expected order

![image](https://user-images.githubusercontent.com/26967164/113080255-2f3fbf80-9209-11eb-9d6e-96aa6f05d5e6.png)

**Comment by dancespiele** [comment]
I think we can close this ticket
