### ISSUE TITLE
WalletSelect | Get the wallet modal to stage 1

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#117]
- [x] Create tabs, expanders or a table with filters? For: 'Tokens' & 'LP Tokens' & 'Synths'
- [x] Map out each of the assets with relevant data
- [x] Dynamic 'Add to wallet' button to add the asset to metamask
- [x] 'View wallet on bscscan' button
- [x] 'Disconnect/change wallet/network' button
- [x] 'Copy address' button
- [x] Details per item TBC but maybe initially 'units held in wallet' & 'units locked in SP' (DAO, collateral etc) separate one for 'bond locked?'
- [x] Plugin icon img from trustWallet repo
- [x] Test trustWallet URL for 404; use fallback if so
- [x] Create and assign fallback img

Standard 'no wallet connected' modal
![image](https://user-images.githubusercontent.com/26967164/113080835-1e437e00-920a-11eb-9e01-13535547404e.png)

Non-metamask wallet (copy contract address)
![image](https://user-images.githubusercontent.com/26967164/113080865-2dc2c700-920a-11eb-943c-f172e53fa3ae.png)

Metamask wallet (add token)
![image](https://user-images.githubusercontent.com/26967164/113080903-4501b480-920a-11eb-92b2-4a38f770952d.png)

LP Tab (This will also need the copy contract or add token button)
![image](https://user-images.githubusercontent.com/26967164/113080925-5054e000-920a-11eb-951d-fb33f2f93037.png)

**Comment by dancespiele** [comment]
is it possible to provide a design?

**Comment by SamusElderg** [comment]
Good point! Have reached out to get one made in Figma 👌

**Comment by SamusElderg** [comment]
@dancespiele mockups as above 👍

**Comment by dancespiele** [comment]
perfect thanks I will continue with this

**Comment by SamusElderg** [comment]
closed with #175
