### ISSUE TITLE
SideBar / Nav | Close on click outside

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#168]
Can we please add a close-on-click-outside of navbar/sidebar thingo?

Currently, when you open the nav/side-bar it stays open until you either select a nav item or press the 'close' icon. Let's have it also close when we click outside the navbar area

![image](https://user-images.githubusercontent.com/26967164/113966078-0a7ac600-9861-11eb-8368-547787fa0f7b.png)

**Comment by dancespiele** [comment]
I think we can close this this ticket that is done
