### ISSUE TITLE
Implement Redux for utils

### ISSUE THREAD

**Issue by dancespiele** [spartan-protocol/SpartanProtocol-DAppV2#19]
In order to optimise and improving the performance we can use Redux and turning all the utils functions as actions then easily  we can use selectors in the views reducing the calls. I can create an example to show how it would work and then we decide if we want to implement it

**Comment by SamusElderg** [comment]
Sounds great thanks! Let us know when you have an example ready

**Comment by dancespiele** [comment]
you can find the example here https://github.com/spartan-protocol/SpartanProtocol-DAppV2/pull/26

**Comment by dancespiele** [comment]
I think we can still use this issue, @SamusElderg could you add all the functions which are complete and it is ready to pass to redux?

**Comment by dancespiele** [comment]
We have splitted already the task in different issues, we don't need this issue anymore
