### ISSUE TITLE
MODAL | Incorrect placement

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#20]
The walletConnect modal (maybe all modals?) places itself at the bottom of the viewport instead of the vertical center

Investigate and ensure 'centered' property in the react-bootstrap modal does the intended vertical-centering

![image](https://user-images.githubusercontent.com/26967164/108786925-a9987680-75af-11eb-9ce1-425983462ef5.png)

**Comment by SamusElderg** [comment]
It's a transform(30) that is causing it

**Comment by SamusElderg** [comment]
this added to the relevant modal css file will fix it:
`transform: none;`

**Comment by dancespiele** [comment]
Also look that is fixed already.
![modal_sparta](https://user-images.githubusercontent.com/29615753/111366700-2345f080-8694-11eb-9d45-bb90ab154e9b.png)
