### ISSUE TITLE
WalletSelect | Get more streamlined

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#201]
Something like this?

![image](https://user-images.githubusercontent.com/26967164/114969480-0bd47000-9eab-11eb-9eea-c38c05aeff64.png)

**Comment by f1ntch** [comment]
![image](https://user-images.githubusercontent.com/12197739/114993668-526e9e00-9e9c-11eb-8ad6-3fe68a56939f.png)
Mobile

**Comment by f1ntch** [comment]
![image](https://user-images.githubusercontent.com/12197739/114993783-703c0300-9e9c-11eb-87ee-d3255f558f02.png)
Desktop
