### ISSUE TITLE
ScrollBar | Style it?

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#214]
Play around with something like the below?

```
::-webkit-scrollbar {
    width: 1px;
}

::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

::-webkit-scrollbar-thumb {
    background-color: #970303;
    outline: 1px solid rgb(0, 0, 0);
  }
```

![image](https://user-images.githubusercontent.com/26967164/115130924-49a9d380-a026-11eb-915f-2ac5248b53d3.png)

instead of:
![image](https://user-images.githubusercontent.com/26967164/115130930-5f1efd80-a026-11eb-9669-ecf9eab83649.png)

**Comment by f1ntch** [comment]
![image](https://user-images.githubusercontent.com/12197739/115139042-10766100-a030-11eb-9290-a763a2c0b26d.png)

**Comment by f1ntch** [comment]
Removed all the other scrollbars in wrappers etc..
