### ISSUE TITLE
LanguageDropdown | Copy across similar

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#215]
Let's get the language dropdown similar to the walletSelect or tokenomics popOver?

![image](https://user-images.githubusercontent.com/26967164/115130996-ee2c1580-a026-11eb-8370-73370ca85910.png)

**Comment by f1ntch** [comment]
![image](https://user-images.githubusercontent.com/12197739/115138467-a4462e00-a02c-11eb-8adb-2721680238f0.png)
