### ISSUE TITLE
Disabled Form z-index issue

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#216]
Lets fix the append icon being broken when the input next to it is disabled=true
z-index issue/fix probably
![image](https://user-images.githubusercontent.com/26967164/115133258-6996c280-a039-11eb-997b-dd5ee367e8f2.png)

Also! The 'button' onClick is no able to be pressed directly ontop of the button; have to go off to the right of it? Can we fix that too?
![image](https://user-images.githubusercontent.com/26967164/115133300-bda1a700-a039-11eb-8808-e91654a3c2da.png)

**Comment by f1ntch** [comment]
![image](https://user-images.githubusercontent.com/12197739/115138656-b8d6f600-a02d-11eb-942f-22a76891ad95.png)
