### ISSUE TITLE
SideBar | Broken on some screen sizes

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#230]
Just change the 10% width for sidebar at the 1200px breakpoint to auto or min-content

![image](https://user-images.githubusercontent.com/26967164/115344957-ac46cf00-a1e0-11eb-9e45-2fc8425970f0.png)

**Comment by jacobostel** [comment]
I would let the menu complete (with text) when the screen is larger than 1200p (maybe a bit less too).
