### ISSUE TITLE
General | Translation 

### ISSUE THREAD

**Issue by f1ntch** [spartan-protocol/SpartanProtocol-DAppV2#232]
Provided with translation on string elements via react-i18next that can be changed via language select menu
![image](https://user-images.githubusercontent.com/12197739/115347973-59562300-a1b2-11eb-9d47-a207849a681a.png)

- [x] Convert from wrapped implementation to hooked
- [x] Cleanup withRouter withNamespaces etc
- [x] Cleanup (props) and props.t() refs
- [x] Cleanup component default exports
- [x] Plugin in an OS SVG bundle of flags
- [x] Setup initial translations based on community GoogleSheet; just focus on menu for now; add a handful of languages and close this phase

**Comment by SamusElderg** [comment]
closed with #236
