### ISSUE TITLE
Liquidity | Cleanup UI

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#265]
- [x] Fix main tabs on smaller screens (Add / Remove / Bond)
- [x] Fix 'add' tabs on smaller screens (Add Both / Add Single)

![image](https://user-images.githubusercontent.com/26967164/115947977-db6d8100-a4fd-11eb-86ad-1a4f42045e63.png)

- [x] Fix 'add' tabs on smaller screens (Remove Both / Remove Single)
![image](https://user-images.githubusercontent.com/26967164/115948009-18d20e80-a4fe-11eb-81ff-386499ee7cda.png)

- [x] Add function to make input.value the balance of the input-asset
- [x] Add colons after 'Balance'
- [x] Make left Cols `xs='auto'`
- [x] Remove 'xs=' from right Cols
- [ ] Add USD-rate-slip to the output LP (see swap)
- [ ] Make the right-col outputs rounded to 6-decimals
![image](https://user-images.githubusercontent.com/26967164/115948183-26d45f00-a4ff-11eb-9e0b-1e24b61e77e3.png)

- [x] Scale the alert text / padding to mobile (way too big on mobile)
- [x] Ensure the above is done for this section too Coll left auto Col right no-xs
- [x] Make sure Col doesn't show up for <Approval> component if not required
![image](https://user-images.githubusercontent.com/26967164/115948255-b37f1d00-a4ff-11eb-9759-0e56ace287f0.png)

**Comment by f1ntch** [comment]
![image](https://user-images.githubusercontent.com/12197739/115954423-4b293f00-a4f1-11eb-9c95-97dcf6045226.png)

**Comment by SamusElderg** [comment]
closed with #274
