### ISSUE TITLE
Wallet connect screen header styling doesn't fit

### ISSUE THREAD

**Issue by dandehavilland** [spartan-protocol/SpartanProtocol-DAppV2#277]
<img width="621" alt="Screenshot 2021-04-24 at 20 53 51" src="https://user-images.githubusercontent.com/95854/115970216-4c825800-a541-11eb-8683-badf647bc025.png">

**Comment by SamusElderg** [comment]
Thats really weird i have never seen that before!

**Comment by SamusElderg** [comment]
What browser, OS and device? And roughly what px width screen?

**Comment by f1ntch** [comment]
Thats fixed can delete

**Comment by SamusElderg** [comment]
Excellent thanks @dandehavilland & @f1ntch !
