### ISSUE TITLE
Add Liquidity: Hide 'Join Pool' button if asset(s) not yet approved

### ISSUE THREAD

**Issue by dandehavilland** [spartan-protocol/SpartanProtocol-DAppV2#286]
![Screenshot from 2021-04-28 06-23-35](https://user-images.githubusercontent.com/95854/116346342-5975a480-a7ea-11eb-8640-46339906ed83.png)

**Comment by dandehavilland** [comment]
@SamusElderg or tweak styles to disable the join button? Doesn't feel right at the moment though

**Comment by SamusElderg** [comment]
> @SamusElderg or tweak styles to disable the join button? Doesn't feel right at the moment though

Absolutely 👍 
The plan is to hide the 'join pool' button if approval is required

**Comment by dandehavilland** [comment]
@SamusElderg I have a question regarding the Approval component:
https://github.com/spartan-protocol/SpartanProtocol-DAppV2/blob/ea7412e6c14c684d0a43617fefcf52e3dca17f6d/src/components/Approval/Approval.js#L63-L94

We're switching on `assetNumber` with the only difference being when `assetNumber==2` then the call to `handleApproval` is `async`. Why `async` on one and not the other?

**Comment by SamusElderg** [comment]
Oh I didn't notice, that would explain the button disappearing too early in some instances 🤣

I'll add the async to the other today thanks buddy

**Comment by dandehavilland** [comment]
No worries - I'll do that since I'm in there anyway
