### ISSUE TITLE
Possible to enter non-numeric characters in Swap and Liquidity inputs

### ISSUE THREAD

**Issue by dandehavilland** [spartan-protocol/SpartanProtocol-DAppV2#304]
Results in `NaN` in calculation results. Should restrict to decimal. 

Options:
- switch to `input#type=number`
- use `inputmode=decimal` and `pattern=[regex goes here]`

**Comment by SamusElderg** [comment]
Awesome thanks buddy, you happy to handle this one?

I was leaning towards (type=number) as long as it doesn't mess with the bignumber text strings (and allows for a decimal place which I believe it does)

Do you have an opinion one way or the other? I trust you 👍

**Comment by SamusElderg** [comment]
I think do type=number and then we can do some thorough testing once the PR is up 👍

**Comment by dandehavilland** [comment]
I did a bit of research and type=number has a few drawbacks, on in particular caught my eye: accidentally scrolling in the input will change your value.

Most other *swap sites use inputmode=decimal so I'd suggest we go with that.

**Comment by SamusElderg** [comment]
> I did a bit of research and type=number has a few drawbacks, on in particular caught my eye: accidentally scrolling in the input will change your value.
> 
> Most other *swap sites use inputmode=decimal so I'd suggest we go with that.

That's a massive drawback! Appreciate you checking that out and saving the headache!

inputmode=decimal makes sense in regards to applying to all inputs to force the numeric keyboard on mobile devices however it will not actually parse/validate the input going in especially on pcs/laptops with a normal keyboard

Let's do a combination:
• inputmode=decimal for all numeric inputs throughout the DApp for better mobile UX
• apply a regex pattern / validation

**Comment by SamusElderg** [comment]
I just realised that exactly what you initially suggested 🤣
Go with that buddy 👍
