### ISSUE TITLE
Add a lightmode theme

### ISSUE THREAD

**Issue by f1ntch** [spartan-protocol/SpartanProtocol-DAppV2#343]
Add a white theme to swap between dark 

- [x] Basic switch function
- [x] Add a SCSS class for white content
- [ ] Check if the color switching works on all components

**Comment by f1ntch** [comment]
![image](https://user-images.githubusercontent.com/12197739/118372195-ad390980-b5b0-11eb-952a-513ba813c9ef.png)

**Comment by SamusElderg** [comment]
@f1ntch can you add the <ThemeSwitcher> to the next PR and remove it from your .gitignore?
For now, I left in all your code and merged it, but commented out the component itself, so will be an easy fix 👍
