### ISSUE TITLE
Footer code polish

### ISSUE THREAD

**Issue by EffyForfax** [spartan-protocol/SpartanProtocol-DAppV2#382]
Inside the footer, an image is listed as;
<a
                href="https://www.reddit.com/r/SpartanProtocol/"
                target="_blank"
                rel="noreferrer"
              >
                {' '}
                <i className="icon-small icon-github icon-dark mr-3" />
              </a>

There is no impact to the output but {' '} is not needed in there.

Tooltip text will be getting added to to aid in navigation of the docs/social medias

**Comment by SamusElderg** [comment]
Sounds good thanks buddy!
