### ISSUE TITLE
Clear input content upon completion of transaction

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/SpartanProtocol-DAppV2#413]
After completing a transaction (below being a removal of 8 DAIp to base assets) the original value of '8' remains  displayed in the input field

![image](https://user-images.githubusercontent.com/72741063/120731076-2ed3e580-c526-11eb-9b0f-0a1c76b48d49.png)

Ensure that this value is cleared upon completion of the Tx

**Comment by SamusElderg** [comment]
I found the values staying there really helpful during the testing phase when doing multiples of the same txns, but I think you are right; its better to clear the inputs for users; better UX in that it helps signal that the txn has gone thru and awaiting a result. Ill look into implementing this soon! Thanks!

**Comment by SamusElderg** [comment]
with rapid testing over; i have implemented this 👍 
see 87f7339bf3f96c53727b37dace7640a46f19d247
