### ISSUE TITLE
Button Shading

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/SpartanProtocol-DAppV2#414]
Similar to previous issue, shade the 'action' button (here - remove liq) to allow users to understand when a tx is pending, and then revert to original colour upon completion of tx

![image](https://user-images.githubusercontent.com/72741063/120731549-3647be80-c527-11eb-8304-cafcdc0c81ee.png)

**Comment by SamusElderg** [comment]
The plan is to have a modal popup with a spinner and when it completes show a link/button to the txn on bscscan. Same as the vault deposit modals (but prettier; they arent finished yet). Do you think that would be suitable or a bit too obtrusive in this faster-moving part of the dapp?

![image](https://user-images.githubusercontent.com/26967164/120821069-b736a280-c587-11eb-8c58-ac8cb3ed94f1.png)

![image](https://user-images.githubusercontent.com/26967164/120821093-bc93ed00-c587-11eb-94e5-bd1ca48bb331.png)

![image](https://user-images.githubusercontent.com/26967164/120821274-e5b47d80-c587-11eb-9d55-b6eb1572254f.png)

**Comment by SamusElderg** [comment]
this is implemented now (albeit slightly different to planned) see: 87f7339bf3f96c53727b37dace7640a46f19d247 and previous commits.

- no txn pending modal (recent txns have their own component now)
- loading spinner shows up on the confirm button now and the inputs clear + spinner disappears after txn is confirmed
