### ISSUE TITLE
Wallet | Calculate & Gamify SPARTA Holdings

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/SpartanProtocol-DAppV2#429]
Calculate a wallet address’ total SPARTA weight and display their effective ranking in the wallet modal.
Include in SPARTA weight:
- [x] SPARTA holdings
- [x] LPs SPARTA spotPrice holdings + staked + bonded
- [x] SYNTHs SPARTA spotPrice holdings + staked

![image](https://user-images.githubusercontent.com/26967164/122522091-257b6a80-d048-11eb-899e-40563eebee4e.png)

**Comment by SamusElderg** [comment]
Thankyou brother! I just padded it out 👍 
Let me know if I missed anything!
