### ISSUE TITLE
Fix copy to clipboard

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#464]
Copy appears to be broken; from memory we commented out and removed a dependency that handle that before; just use the internal js function instead

**Comment by tominou** [comment]
Copy seems fine but the alert is commented.
Should we implement a "Toast" system ? or use boostrap's one ?

**Comment by SamusElderg** [comment]
> Copy seems fine but the alert is commented.
> Should we implement a "Toast" system ? Or use boostrap's one ?
> 
> Edit: Yes we surely can remove the plugin to use native javascript fct

Copy definitely wasn't working in the wallet and asset select modals; but i see your PR so all good will check and merge it; thanks buddy!

**Comment by SamusElderg** [comment]
Solved; can now be closed
