### ISSUE TITLE
Double-Swap estimate fix

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/SpartanProtocol-DAppV2#469]
![image](https://user-images.githubusercontent.com/72741063/126605925-e73196a3-c870-4073-932f-8dfd074773c2.png)

Double-Swap fee estimate is not accurately calculating the fee for TOKEN1-SPARTA and SPARTA-TOKEN2 swaps, also check synths swaps and pool token swaps etc

**Comment by SamusElderg** [comment]
Thanks @SP-Nate !
Most of this code was replaced with 865af52f67fdd123f8f43f738990d60529b68465 and some earlier commits; can confirm it is no longer an issue 👍
