### ISSUE TITLE
BUG | Misleading "confirm" button in Vault-deposit

### ISSUE THREAD

**Issue by t1-dev** [spartan-protocol/SpartanProtocol-DAppV2#475]
**Describe the bug**
On testnet, in the "Vault" window, depositing BNBp and pressing "confim" button, this initiates the Tx in the wallet, but there is still a button "confirm" in the window where the rotating logo is.

This button should not be pressed otherwise a new, additional, tx would be initiated.
And when the tx has been confirmed in the wallet, the "confirm" button is still there, and would still launch a new tx if pressed.

**Expected behavior**
There should not be this button "confirm" when the Tx is already in processing by the wallet.

**Desktop (please complete the following information):**
MetaMask on Chrome, windows 10

**Comment by SamusElderg** [comment]
Thankyou my friend 👍 
This extra modal-bloat has been removed as of: b27616a4f9470d387f9ff3c1362d35559122cfb9
There are plans to simplify this and add states to the buttons instead of stages to the modal. Later phase will have the pending txn pop up probably top-right as a toast too
