### ISSUE TITLE
Light/White Day-Time Mode

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#514]
**Update the stylesheets to cater for day-time mode:**
- Align the light-mode style to match the Figma
- Discussion would be good here; but below are the mockups for inspiration
- Please comment here or in Telegram to put your hand up to help with this task!

![image](https://user-images.githubusercontent.com/26967164/134677839-ce5762dc-c775-4958-a944-3bdac6a6ed48.png)

![image](https://user-images.githubusercontent.com/26967164/134677870-be22a6b2-014b-4260-b2cb-ece6162bf63c.png)

![image](https://user-images.githubusercontent.com/26967164/134677956-a18d4a2b-2321-4951-89e8-8c5be3ec7f53.png)

![image](https://user-images.githubusercontent.com/26967164/134677987-f6b345b0-072a-45d7-ba0d-58d52fb8dda3.png)

![image](https://user-images.githubusercontent.com/26967164/134678008-5947da12-3dd9-4205-8ec0-84fd551c33d5.png)

**Comment by SamusElderg** [comment]
@jacobostel & @tominou you have both signalled interested in helping with the light-mode color palette so feel free to touch base with each other or discuss openly in here (or the dev chat) if you would like to coordinate on this

**Comment by tominou** [comment]
Actually, I tried to make some changes on actual code but always ended up giving up because of the heaviness of the code.

So I am now working on the UI from a blank React project, then once I have something satisfying for everyone we can discuss what is the best way to implement it on the app.

**Comment by tominou** [comment]
Right now I haven't added bootstrap yet. I use to go vanilla, then add things when I feel the need.

I pushed the code here: https://github.com/tominou/spartan-protocol-dapp

Let me know if I am going on the right way or not, and if anyone want to participate, maybe we can create a repo on this Github ?

**Comment by SamusElderg** [comment]
Looking great so far (menu/header/colour theme of main components) definitely heading in the right direction buddy!
The custom components are nice and compact/small in code which i appreciate too, will be a lot easier this way to migrate to the new style and rip out the component library without breaking things 👍

**Comment by jejopl** [comment]
What's the status of this one? Is someone working on it?
