### ISSUE TITLE
Dynamic Token SVG | Concat SVG data to overlay icons

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#545]
Currently with things like the BNBs (synth) and BNBp (LP token) we grab two SVGs:
- original token icon (BNB)
- sparta alt icon (SPARTA icon with modified colour based on type)
And we pop them in a container with the use of position:absolute and location assignments like left:10px & top:20px etc

Let's explore whether we can concat the SPARTA alt icon SVG after the TOKEN icon SVG and create a custom SVG.
If possible and consistent enough with the varying SVGs from all the different projects; ideally create a helper function to perform this action and place the SPARTA alt SVG in the bottom-right corner of the TOKEN SVG and return it to any place in the dapp we might need it.

Will likely need to make the TOKEN SVG a fixed size first that is (~300%??) larger than the SPARTA alt SVG so that we get consistent sizing and placement of the overlayed SPARTA alt SVG

If/when this is done and successful; we then need to gradually go thru the codebase and update all usages of the previous method:
- MetaMask watchAsset action (highest priority as it currently is just a plain TOKEN svg)
- AssetSelect
- WalletSelect
- SwapPair
- Bond
- DaoVault
- SynthVault

**Comment by jacobostel** [comment]
If the code of creating an SVG with every 2 SVG needs to be run on every local environment, I think it is good as it is right now.
But I still see it as a good to have for the 'add to metamask' function, to have the proper icon on metamask.

**Comment by SamusElderg** [comment]
Lets close this one for now, no need to do any complex extra features for this DApp if focus shifts to the swap aggregator
