### ISSUE TITLE
<0.01$ token price not showing in dapp

### ISSUE THREAD

**Issue by DnJoey** [spartan-protocol/SpartanProtocol-DAppV2#556]
Price of token not showing when <0.01$ in the dapp (example as for RAVEN )
![Screenshot_20211005-194448_Brave](https://user-images.githubusercontent.com/72745673/136092177-18c386bb-fab0-4a55-a3a8-85753c8719c4.jpg)

**Comment by SamusElderg** [comment]
closes with 4a51e9699f0fa096314a147661cd832b3f73f2d7
