### ISSUE TITLE
Create Pool | Add upper-check for 100K

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#642]
In the create pool component, we need to add an upper check to ensure the user does not add more than 100K SPARTA (the default pool cap) otherwise txn wont be possible anyway (will revert in `Pool._incrementPoolBalances` without a revert message)

**Comment by SamusElderg** [comment]
@jacobostel do you want this one?

**Comment by jacobostel** [comment]
works
