### ISSUE TITLE
Partnership Page | Add CoinGecko

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#739]
CoinGecko have requested us to add a link to them in the DApp which of course would be great.
While at it, lets change the 'Partners' page name to something less direct/insinuating, like 'Friends'

Lets then pop CoinGecko in there:
- https://www.coingecko.com/en/branding
- Use wide/flat logo: https://drive.google.com/drive/folders/1qXUuFJB-Gk2g91vyI-Qt58Z_49FLsjsZ
- "SPARTA market price provided by CoinGecko."

**Comment by jejopl** [comment]
Here's PR for this one - #744

**Comment by SamusElderg** [comment]
closes with #744
