### ISSUE TITLE
Prettier | Change to warning only 

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#76]

**Comment by dancespiele** [comment]
I think that setting the prettier plugin to fix all the linter issues automatically for each save is expending less time than every time disabling and enabling prettier.

Vscode: in settings.json file just include:
```
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    },
```
Webstorm: https://www.jetbrains.com/help/webstorm/prettier.html#ws_prettier_reformat_code
