### ISSUE TITLE
Theme Color Suggestions | Primary / Secondary / Success ... etc

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#761]
Please direct all suggestions to do with theme colors here and please take time and try not to be broad with suggestions. Ideally provide examples and HEX color codes etc

Keep the discussion here on point of 'colors' in regards to 'primary', 'secondary', 'info' etc, please.

### For a little understanding this is generally how it works:

**Theme colors:**
We have 8 theme colors to use throughout every component we use, the below example is the current temporary ones in use

![image](https://user-images.githubusercontent.com/26967164/164579678-3f11a242-e2e5-4bc5-a8f4-76a9c5c04675.png)

When we change those colors it has effects on every component, for some important examples, see the below

**Component examples:**
Buttons
![image](https://user-images.githubusercontent.com/26967164/164579807-6aa2a9e9-dadd-475b-9e8c-fb08ef00a2ee.png)
Outline buttons
![image](https://user-images.githubusercontent.com/26967164/164579850-4875dac3-749f-4512-ae69-ad2855eca56b.png)
Button groups
![image](https://user-images.githubusercontent.com/26967164/164579990-e6b7086a-eee4-494c-a7cd-28c0a91d641a.png)
Alerts
![image](https://user-images.githubusercontent.com/26967164/164579896-95bb8f71-b0a5-4351-9afb-01fee89d282b.png)
Badges
![image](https://user-images.githubusercontent.com/26967164/164579938-84b3dbe6-fa84-47f7-9eb0-1e29da6e677e.png)
Badge pills
![image](https://user-images.githubusercontent.com/26967164/164579954-cdfde9c2-5f13-4b67-8ed9-ab0edf78b312.png)
Progress bars
![image](https://user-images.githubusercontent.com/26967164/164580099-cba3a5be-6c7c-4b02-b146-9446aa42030f.png)

### Structural component colors
The background colors of the more structural components like:
- side navbar
- top navbar
- entire app background
- card body/header/footer
- popover header/body
- modal header/body/footer etc

Suggestions for these are also welcome, but don't expect anything to be actioned until there is some proper mockup work done by a pro in the field, i would rather contributors don't waste time playing around with temporary colors unless of course they want to, or feel they might be able to put together a final product on the fly or a temporary one pretty easily (you are welcome to tackle the issue if you want to of course, just don't feel *pushed* to temporarily change a color here and there by anyone else)

Branding pros, feel free to contribute mockups & color palettes 

Feel free to change CSS colors/styles via the inspector in your browser and provide screenshots if you are feeling adventurous:
![image](https://user-images.githubusercontent.com/26967164/164581155-c3c41b7f-1d10-441c-8811-cb822eb1388e.png)
![image](https://user-images.githubusercontent.com/26967164/164581236-871ef8b2-e6b1-411f-80c0-bc7eb2abbb25.png)
![image](https://user-images.githubusercontent.com/26967164/164581261-0a56223c-cab5-454c-82dc-92f3ce6a228b.png)
![image](https://user-images.githubusercontent.com/26967164/164581307-8857aecd-6189-4e23-8b28-7a10c0291ac8.png)
![image](https://user-images.githubusercontent.com/26967164/164581317-516d474e-4ea0-4168-8076-b09d3f6ba2a6.png)

**Comment by ArthurvdDriest** [comment]
Maybe in line with the colorscheme of the new landing page as that's being redesigned?
