### ISSUE TITLE
Add 4tech to 'Friends' page

### ISSUE THREAD

**Issue by foot-job** [spartan-protocol/SpartanProtocol-DAppV2#769]
![4thTech-Dark-SVG-2K](https://user-images.githubusercontent.com/102369003/165420524-5e1e6a50-311e-4819-9f95-861fe3a7f434.svg)

https://4thtech.io/

Adding in our good friends providing Dchat, Dmail to friends page on spartan protocol https://dapp.spartanprotocol.org/friends
hoping to involve more Spartans in using and testing this technology

offering rewards if people want to help out in dchatting and sending dmails (testing)

**Comment by SamusElderg** [comment]
Will add two buttons, one for 'View Portal' (login to dChat/dMail) and one for 'View 4thTech' (Their website)

**Comment by foot-job** [comment]
Thanks samus

**Comment by SamusElderg** [comment]
closes with c6c097a5feee6f513627e59114fe66f50cc4b892
