### ISSUE TITLE
Add padding to bottom of body

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#783]
In some mobile browsers, if you scroll to the bottom of the page, some elements are partially hidden by browser toolbars

Doesn't seem to be an issue with sections that come into the DOM on demand like the mobile side menu

Let's just add a chunk of padding to the bottom of the body section so that the bottom of the page is still potentially hidden in some cases but unimportant as it's just padding 

Proposed solution to work off:
in `global.scss` inside `.body` add in:
`padding-bottom: 120px;`

**Comment by jejopl** [comment]
I think that it's because some mobile browsers don't like `100vh` in style. The padding seems like the best/quickest solution 👍
