### ISSUE TITLE
Friends | Add View DEX to CG

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#793]
- [x] Add 'View DEX' button to CoinGecko friend item

![IMG_20220525_144528.jpg](https://user-images.githubusercontent.com/26967164/170197787-c997dac4-f138-46d0-8ea2-be0f798a8de8.jpg)

**Comment by jejopl** [comment]
@SamusElderg done #794

**Comment by SamusElderg** [comment]
Thankyou @jejopl !
