### ISSUE TITLE
BUG | Missing favicon

### ISSUE THREAD

**Issue by jejopl** [spartan-protocol/SpartanProtocol-DAppV2#824]
The favicon is not displayed on the browser
<img width="397" alt="image" src="https://user-images.githubusercontent.com/32012330/178226613-8481f828-777a-451e-a9a8-25f6113b06b8.png">

**Comment by SamusElderg** [comment]
I cant seem to re-create this. Maybe MAC-specific? (Fine on android and windows, checked a bunch of browsers too)
If its mac specific, its probably an easy one to find, to do with native .svg compatibility for favicons maybe? We have an .ico there in the public folder too we can test for mac

**Comment by SamusElderg** [comment]
Lets maybe remove both favicon headers and replace it with one PNG favicon for compatibility for everything except old IE 6-10 & opera mini. If we also add an ICO, safari should use it though, so maybe the ICO favicon is broken or rendered wrong or something (or the header tag is wrong?)

**Comment by jejopl** [comment]
@SamusElderg I just tested it and it works fine on chrome. This issue is happening on firefox

**Comment by SamusElderg** [comment]
> @SamusElderg I just tested it and it works fine on chrome. This issue is happening on firefox

What about safari? Wierd that firefox has issues, pretty sure its supported SVG favicons pretty much forever.

**Comment by jejopl** [comment]
Not working on Safari either. The weird part is that the favicon was there for a split second and then it transitioned to default one 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/32012330/178250208-ca336841-041a-41fd-a4df-4d05b0ea2dae.png">

**Comment by jejopl** [comment]
I found the issue:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/32012330/178250802-c0cadfa7-5c15-47fa-9bd8-77a89e74fd05.png">

**Comment by jejopl** [comment]
I think it's because the favicon is saved in inkscape format. I'll convert it to normal svg
<img width="938" alt="image" src="https://user-images.githubusercontent.com/32012330/178250974-87a3da85-706e-4b12-8bc4-9e6d9113f96c.png">

The same thing is happening on chrome but it's using .ico instead. That's why it works

**Comment by SamusElderg** [comment]
> I think it's because the favicon is saved in inkscape format. I'll convert it to normal svg <img alt="image" width="938" src="https://user-images.githubusercontent.com/32012330/178250974-87a3da85-706e-4b12-8bc4-9e6d9113f96c.png">
> 
> The same thing is happening on chrome but it's using .ico instead. That's why it works

Good job! I thought i went thru and ripped out the excess meta of every .svg but must have missed some! Lets maybe make a github issue to run thru all svgs and do some spring cleanup checks. I always save as 'optimized svg' now. I think we might also be able to add a test unit to scan and check all svgs for illegal characters on merge too, might be something good to add for the future

**Comment by jejopl** [comment]
#825 this PR should fix that one
