### ISSUE TITLE
Spring Cleanup | Check/convert all SVGs to optimized

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#826]
Lets run thru every SVG and make sure they are all optimized format instead of 'inkscape' etc with the complex props and illegal characters

- [x] Check and convert every SVG in the repo
- [ ] Investigate adding a unit test to check for some common illegal/incompatible characters in SVGs

**Comment by jejopl** [comment]
#828
