### ISSUE TITLE
V2 Contracts | Link DAppV2 -> ContractsV2 (Phase 1)

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#84]
Dependancy:
- [x] Deploy fresh SpartanContractsV2 (After this is ticked we may start the below)

### After fresh SpartanContracts V2 deploy, remap/update everything relevant in DAppV2:

**ABI JSONs**
- [x] MN ABIs files (SpartanContracts V2)
- [x] TN ABIs files (SpartanContracts V2 - same as above for now)
- [x] OLD ABIs files (Make sure copies of all old ABIs go in here)

**Web3 Utils (Just update the consts)**
- [x] utils/web3.js (ABI links, all addresses)

**Web3 Utils (New functions)**
- [x] Setup the below files with their relevant `getXXXXXContract(`) function ready and populated
- [x] utils/web3DaoVault.js (Add all new non-async functions)
- [x] utils/web3Pool.js (Add all new non-async functions)
- [x] utils/web3PoolFactory.js (Add all new non-async functions)
- [x] utils/web3Loan.js (Add all new non-async functions)
- [x] utils/web3LoanVault.js (Add all new non-async functions)
- [x] utils/web3Migrate.js (Add all new non-async functions)
- [x] utils/web3Synth.js (Add all new non-async functions) **ROUTER HANDLES THIS**
- [x] utils/web3SynthFactory.js (Add all new non-async functions) **ROUTER HANDLES THIS**

**Synth Store (Ref: synth.sol)**
- [x] Create a store for 'Synth' **ROUTER HANDLES THIS, MAYBE NEXT PHASE**
- [x] Add in relevant async actions, types etc for the additional contracts **ROUTER HANDLES THIS, MAYBE NEXT PHASE**

**SynthFactory Store (Ref: synthFactory.sol)**
- [x] Create a store for 'SynthFactory' **ROUTER HANDLES THIS**
- [x] Add in relevant async actions, types etc for the additional contracts **ROUTER HANDLES THIS**

**Fix/Update Bond (Some contract function names or params may have changed)**
- [x] Compare Bond store to new contract
- [x] Add new functions to web3 ready for conversion to store
- [x] Convert them into the bondStore

**Fix/Update Dao (Some contract function names or params may have changed)**
- [x] Compare Dao store to new contract
- [x] Add new functions to web3 ready for conversion to store
- [x] Convert them into the daoStore

**Fix/Update Router (Some contract function names or params may have changed)**
- [x] Compare Router store to new contract
- [x] Add new functions to web3 ready for conversion to store
- [x] Convert them into the routerStore

**Fix/Update Utils (Some contract function names or params may have changed)**
- [x] Compare Utils store to new contract
- [x] Add new functions to web3 ready for conversion to store
- [x] Convert them into the utilsStore

**Fix/Update UtilsMath (Some contract function names or params may have changed)**
- [x] Compare UtilsMath store to new contract
- [x] Add new functions to web3 ready for conversion to store
- [x] Convert them into the utilsMathStore

**Fix/Update UtilsPricing (Some contract function names or params may have changed)**
- [x] Compare UtilsPricing store to new contract
- [x] Add new functions to web3 ready for conversion to store
- [x] Convert them into the utilsPricingStore

**Comment by dancespiele** [comment]
I can work in the pools store but I need the functions first
