### ISSUE TITLE
Change default theme to dark mode

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#888]
As per issues title, let's change the default theme mode to "dark" instead of light

**Comment by jejopl** [comment]
@SamusElderg maybe we could use user's system settings for this one?

**Comment by ArthurvdDriest** [comment]
> @SamusElderg maybe we could use user's system settings for this one?
> 
> We could use js to detect it `if(window.matchMedia('(prefers-color-scheme: dark)').matches) {}`

Ive got this implemented and running on a branch

**Comment by SamusElderg** [comment]
Pretty keen to just make dark the default until/if/after we get the light mode theme looking alot nicer, so maybe we can use @ArthurvdDriest code but have it commented out and ready?

But flip the default for now to dark (if we do this we must make sure we use a completely new var name in localStorage + redux to reset user settings etc

**Comment by SamusElderg** [comment]
If agreed, @ArthurvdDriest can you make a PR or let me know the branch, and I'll add to that and we can merge that in ready to roll 👌

**Comment by ArthurvdDriest** [comment]
Not quite sure what you mean with the variable in localstorage + redux (still finding my way around all the files and javascript in general). i see it being used in toggleDark() which i assume is for the button to toggle light/dark mode? Currently i made it so that onLoad() checks the users prefered system-theme and change it to dark if it isnt.

Branch: 'change-default-theme#888'

**Comment by SamusElderg** [comment]
> Not quite sure what you mean with the variable in localstorage + redux (still finding my way around all the files and javascript in general). i see it being used in toggleDark() which i assume is for the button to toggle light/dark mode? Currently i made it so that onLoad() checks the users prefered system-theme and change it to dark if it isnt.
> 
> Branch: 'change-default-theme#888' Not sure if im added to the repo yet to submit a PR.

Thanks i see the PR, will have a look soon, also in regard to the localStorage and redux handling no stress, ill handle it and show you what i mean.

Essentially if we flip the default with the same vars, any user who previously visited the DApp and had light mode forced on them (but they didn't specifically choose it or even know dark mode was available) will continue to have light mode (because it sets the previous default as their preference which persists in the local storage of their browser) 

Whereas if we do a new var it will be looking for a preference setting in local storage for new and old users that doesn't exist (first load) so every user new & old will be forced into the darker theme and can choose (if they wish to) flip it to light mode and then that will persist as their specific preference from there-on. 

ie. changing the vars in localStorage + redux will mean all users are actually dark mode by default and will have to consciously choose light mode if they want it which will persist from there-on with the same device/browser

**Comment by ArtyODonnell** [comment]
> Essentially if we flip the default with the same vars, any user who previously visited the DApp and had light mode forced on them (but they didn't specifically choose it or even know dark mode was available) will continue to have light mode (because it sets the previous default as their preference which persists in the local storage of their browser)
> 
> Whereas if we do a new var it will be looking for a preference setting in local storage for new and old users that doesn't exist (first load) so every user new & old will be forced into the darker theme and can choose (if they wish to) flip it to light mode and then that will persist as their specific preference from there-on.
> 
> ie. changing the vars in localStorage + redux will mean all users are actually dark mode by default and will have to consciously choose light mode if they want it which will persist from there-on with the same device/browser

I see, thought the specified var was referenced to LocalStorage somewhere but couldn't find it, but it just exists only within the said file.

**Comment by SamusElderg** [comment]
Closed with #890
