### ISSUE TITLE
TEST | Fix all the tests

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#96]
Let's look at fixing relevant tests and removing/commenting out any that require some transaction/proposal/bond etc history

- [x] store/bond/actions.test.js
- [x] store/dao/actions.test.js
- [x] store/router/actions.test.js
- [x] store/sparta/actions.test.js
- [x] store/utils/actions.test.js
- [x] store/utilsMath/actions.test.js
- [x] store/utilsPricing/actions.test.js
- [x] store/web3/actions.test.js

**Comment by dancespiele** [comment]
the utils.test.js shouldn't be deleted however I will need to create more tests the new functionalities

**Comment by SamusElderg** [comment]
Thanks! i removed that last item on the checklist then 👍
