### ISSUE TITLE
Redux DevTools | Enable redux devtools

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#97]

**Comment by dancespiele** [comment]
This I can take care if you want

**Comment by SamusElderg** [comment]
> This I can take care if you want

Already done buddy, see the referenced commit above 👍

Thanks though!

![IMG_20210323_072640.jpg](https://user-images.githubusercontent.com/26967164/112070706-32073880-8ba9-11eb-9867-fe5accd9fa58.jpg)
